### ISSUE TITLE
Latest canary update broke pretty much everything

### ISSUE THREAD

**Issue by sylveon** [AlexFlipnote/Discord_Theme#83]

**Comment by Takeoverkyle** [comment]
Confirming this as well, but it's not everything after looking around. Seems to be the top title bar that is mis-colored and text box that's now higher than the mic/headphone/setting bar. All other boxes and settings when clicked on seem to be normal.

**Comment by sylveon** [comment]
Chat box is also taking full width when it shouldn’t. Transparent doesn’t works either.

**Comment by KurozeroPB** [comment]
```css
.titleBar-3_fDwJ {
  background: #181818;
}

.container-iksrDt {
  background: #181818;
}

.chat.flex-vertical.flex-spacer .title-qAcLxz {
  background: #212121;
}

.flex-spacer.flex-vertical form {
  background: #212121;
}

.channelTextAreaEnabled-c05Zpy.channelTextArea-1HTP3C.channelTextArea-os01xC {
  background: #212121;
}

.innerEnabled-gLHeOL.inner-3if5cm.flex-3B1Tl4.innerNoAutocomplete-kaUXJZ {
  background: #212121;
  border-radius: 0;
  margin-bottom: -1.6em;
  margin-top: 0.3em;
}
```
Should be a quick fix for anyone locally, it's a hacky way of doing things but it works xD
